# Generated by Django 3.2.9 on 2021-12-09 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20211209_1650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='user1',
            new_name='user',
        ),
    ]
